### ISSUE TITLE
Download FTP script: wrong URL for old versions

### ISSUE THREAD

**Issue by grafitos** [TMiguelT/vep-cache-extractor#1]
Hi,

The URL generated to download cache is wrong for older versions (for example 75) : Genome version is not specified in the filename.

ftp://ftp.ensembl.org/pub/release-${ENSEMBL_RELEASE}/variation/VEP/${CACHE_TYPE}_${ENSEMBL_RELEASE}_GRCh${GENOME_BUILD}.tar.gz

should be

ftp://ftp.ensembl.org/pub/release-${ENSEMBL_RELEASE}/variation/VEP/${CACHE_TYPE}_${ENSEMBL_RELEASE}.tar.gz

**Comment by multimeric** [comment]
Thank you very much for pointing this out! This should be fixed in 5525bff (https://github.com/TMiguelT/vep-cache-extractor/blob/master/download.sh#L62-L66)
