### ISSUE TITLE
Works only under KSH

### ISSUE THREAD

**Issue by grafitos** [TMiguelT/vep-cache-extractor#2]
Hi,

Download.sh script is only working under KSH shell ( ****.gz** syntax ).

**find vep_cache -name '*.gz' -exec gunzip {} \;** ?

**Comment by multimeric** [comment]
This shoooulld be fixed by fd7b6a9. I partially tested it, but not start to finish, so if you could check that out it would be fantastic.

**Comment by multimeric** [comment]
Actually, I realise I updated the extractor script a while ago to not require an unzipped vep cache, so this is actually no longer needed, so I removed this from the download script and updated the documentation. I hope that helps!

Please keep me updated with any other bugs you notice.
